### ISSUE TITLE
Formatting issue with Outputs Current/ Proposed state

### ISSUE THREAD

**Issue by sharan-aadarsh** [im2nguyen/rover#35]
The output state is coming as an individual array elements.

![image](https://user-images.githubusercontent.com/36393191/135060690-6b2668ea-642e-4506-b808-2eae47ce704d.png)

**Comment by im2nguyen** [comment]
Thanks for reporting @sharan-aadarsh! Just came across this while testing, will address it in the next release 😄

**Comment by im2nguyen** [comment]
This should be fixed with #32! Can you pull the latest Docker image and test it again? You can also re-download the binary 😄 

```
docker pull im2nguyen/rover
```

**Comment by sharan-aadarsh** [comment]
Thanks, @im2nguyen for the quick fix, the proposed state shows the correct value but in the current state, the issue still persists.

**Comment by im2nguyen** [comment]
Sorry about that, just pushed the version that also fixes current state. Can you pull and try again?

**Comment by sharan-aadarsh** [comment]
with the latest binaries, I'm not able to access the application on localhost , with old one it is running
![image](https://user-images.githubusercontent.com/36393191/135233508-97cdd93c-c9a4-4db0-ba22-ac1222398729.png)

**Comment by sharan-aadarsh** [comment]
@im2nguyen , thanks for the fix, works like a charm
