### ISSUE TITLE
Add Support for Terraform Version 1.1.7

### ISSUE THREAD

**Issue by ncecere** [im2nguyen/rover#99]
Failed to read plan from plan file: plan file was created by Terraform 1.1.7,
but this is 1.1.2; plan files cannot be transferred between different
Terraform versions.

Please add support for Terraform 1.1.7

**Comment by im2nguyen** [comment]
This should be addressed with the latest release! It should now be at v1.2.5

**Comment by pneigel-ca** [comment]
Hi,

I am trying to run rover v0.3.3 in a docker container but I'm still receiving an error. Here's the version constraint from my provider.tf:

```tf
terraform {
  required_version = ">= 1.1.7"
}
```

Here's how I'm invoking rover:

`docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover:v0.3.3 -tfVarsFile ./test/terraform.tfvars -standalone true`

I receive this output:
```
2022/09/12 23:56:56 Starting Rover...
2022/09/12 23:56:56 Initializing Terraform...
2022/09/12 23:56:57 Unable to parse Plan: Unable to initialize Terraform Plan: terraform 1.1.2 not supported by configuration (>= 1.1.7 required)
```
